package com.example.util

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object AppStrings {
    var activeLanguage by mutableStateOf("fa") // default is Persian

    private val en = mapOf(
        "app_title" to "Smart Planner",
        "today" to "Today",
        "tasks" to "Tasks",
        "goals" to "Goals",
        "calendar" to "Calendar",
        "analytics" to "Analytics",
        "settings" to "Settings",
        "back" to "Back",
        "save" to "Save",
        "cancel" to "Cancel",
        "add_task" to "Add Daily Task",
        "edit_task" to "Edit Task",
        "add_goal" to "Add Goal",
        "edit_goal" to "Edit Goal",
        "task_title" to "Task Title",
        "task_subtitle" to "Details/Description",
        "priority" to "Priority",
        "priority_low" to "Low",
        "priority_med" to "Medium",
        "priority_high" to "High",
        "due_date" to "Due Date",
        "folder" to "Category / Folder",
        "no_folder" to "General",
        "folders" to "Categories",
        "all_tasks" to "All Actions",
        "add_folder" to "Create Category",
        "folder_name" to "Category Name",
        "color" to "Color",
        "streak_day_counter" to "Habit & Streak Tracker",
        "streak_subtitle" to "Maintain your positive actions, tick daily",
        "active_streaks" to "Active Streak",
        "best_streak" to "Best Record",
        "days" to "Days",
        "unmarked" to "Not Ticked",
        "ticked" to "Ticked Today!",
        "un_tick" to "Untick",
        "tick" to "Tick Today",
        "no_tasks_today" to "No tasks scheduled for today. Rest or add a task!",
        "percentage_done" to "Done",
        "completion_rate" to "Productivity & Completion Rate",
        "last_7_days" to "Productivity - Last 7 Days",
        "goal_target" to "Goal Target Date",
        "progress" to "Progress",
        "no_goals" to "No active goals in this category.",
        "gregorian" to "Gregorian (Miladi)",
        "jalali" to "Persian (Shamsi)",
        "hijri" to "Islamic (Qamari)",
        "cloud_sync" to "Cloud Sync (Backup)",
        "sync_now" to "Sync Now",
        "synced_just_now" to "Successfully backed up to your account cloud storage!",
        "last_sync" to "Last Synced",
        "select_theme" to "Theme Presets",
        "theme_light" to "Cream Light Mode",
        "theme_dark" to "Cosmic Dark Mode",
        "theme_amoled" to "Amoled Deep Theme",
        "language" to "Application Language",
        "en" to "English (US)",
        "fa" to "فارسی (Persian)",
        "reminder_notification" to "Reminder Notifications",
        "enable_notifications" to "Enable Reminders",
        "remind_me_at" to "Set Remind Time",
        "reminder_set" to "Reminder set successfully",
        "notification_history" to "Smart Notifications",
        "analysis_positive" to "You did fantastic yesterday! Your completion rate increased.",
        "analysis_neutral" to "Stable productivity. Keep pushing forward to hit your targets!",
        "analysis_negative" to "A minor dip in completion. Don't worry! Every step forward counts.",
        "weekly_overview" to "Weekly Engagement Overview",
        "habit_tracker" to "Habit Tracker",
        "add_habit" to "Add Habit",
        "habit_title" to "Habit Name (e.g. Daily Exercise)",
        "stats_summary" to "Efficiency Breakdown",
        "important_alerts" to "Daily Highlight Messages",
        "status_completed" to "Completed",
        "status_pending" to "Pending",
        "all_categories" to "All Folders",
        "search_advanced" to "Advanced Search",
        "search_query" to "Search keyword...",
        "order_by" to "Sorted By",
        "order_date" to "Date Scheduled",
        "order_priority" to "Importance Level",
        "no_results" to "No matches found with current filters",
        "search" to "Search",
        "negative_habit" to "Negative Habit (Avoid/Break)",
        "positive_habit" to "Positive Habit (Action/Growth)",
        "habit_type" to "Habit Behavior",
        "group" to "Family/Group Sync",
        "group_code" to "Family Share Code",
        "group_code_placeholder" to "e.g., FAMILY_AURA",
        "group_sync_status" to "Group Synced",
        "all_priorities" to "All Priorities",
        "no_tasks_today_completion" to "No tasks registered today",
        "percentage_avoided" to "Avoided",
        "history" to "History",
        "performance" to "Activity History & Daily Tracker",
        "no_history" to "No activity logged yet.",
        "view_history" to "History & Chart",
        "habit_progress" to "Habit Completion Chart",
        "show_full_history" to "Show Full History",
        "close" to "Close",
        "all_records" to "All Logs",
        "days_total" to "Total Completed Days"
    )

    private val fa = mapOf(
        "app_title" to "برنامه‌ریز هوشمند",
        "today" to "امروز",
        "tasks" to "برنامه‌ها",
        "goals" to "اهداف",
        "calendar" to "تقویم",
        "analytics" to "تحلیل بازدهی",
        "settings" to "تنظیمات",
        "back" to "بازگشت",
        "save" to "ذخیره",
        "cancel" to "لغو",
        "add_task" to "افزودن برنامه روزانه",
        "edit_task" to "ویرایش برنامه",
        "add_goal" to "افزودن هدف جدید",
        "edit_goal" to "ویرایش هدف",
        "task_title" to "عنوان برنامه",
        "task_subtitle" to "توضیحات / جزئیات",
        "priority" to "اولویت",
        "priority_low" to "کم",
        "priority_med" to "متوسط",
        "priority_high" to "زیاد",
        "due_date" to "تاریخ انجام",
        "folder" to "دسته‌بندی / پوشه",
        "no_folder" to "عمومی",
        "folders" to "پوشه‌ها",
        "all_tasks" to "همه کارها",
        "add_folder" to "ایجاد دسته‌بندی جدید",
        "folder_name" to "نام دسته‌بندی",
        "color" to "رنگ",
        "streak_day_counter" to "روزشمار عادت و استمرار",
        "streak_subtitle" to "پایداری بر کارهای مثبت روزانه را با تیک ثبت کنید",
        "active_streaks" to "روزهای متوالی",
        "best_streak" to "بهترین رکورد",
        "days" to "روز",
        "unmarked" to "تیک نخورده",
        "ticked" to "ثبت شده برای امروز!",
        "un_tick" to "لغو تیک امروز",
        "tick" to "ثبت تیک امروز",
        "no_tasks_today" to "هیچ برنامه‌ای برای امروز تعریف نشده است. استراحت کنید یا مأموریت جدید اضافه کنید!",
        "percentage_done" to "انجام شده",
        "completion_rate" to "درصد موفقیت و تکمیل برنامه‌ها",
        "last_7_days" to "نمودار بازدهی ۷ روز اخیر",
        "goal_target" to "تاریخ اتمام هدف",
        "progress" to "میزان پیشرفت",
        "no_goals" to "هیچ هدفی در این دسته‌بندی وجود ندارد.",
        "gregorian" to "میلادی",
        "jalali" to "شمسی",
        "hijri" to "قمری",
        "cloud_sync" to "همگام‌سازی ابری",
        "sync_now" to "همگام‌سازی سریع",
        "synced_just_now" to "پشتیبان‌گیری با موفقیت در فضای ابری حساب کاربری شما ذخیره شد!",
        "last_sync" to "آخرین همگام‌سازی",
        "select_theme" to "پوسته نرم‌افزار",
        "theme_light" to "روشن (کرم و خامه)",
        "theme_dark" to "تیره (کاسمیک سنتر)",
        "theme_amoled" to "فوق‌تیره (آمولد بلک)",
        "language" to "زبان برنامه",
        "en" to "English (US)",
        "fa" to "فارسی (Persian)",
        "reminder_notification" to "سیستم یادآوری اعلان‌ها",
        "enable_notifications" to "فعال‌سازی آلارم برنامه‌ها",
        "remind_me_at" to "تنظیم زمان زنگ یادآوری",
        "reminder_set" to "یادآور با موفقیت ثبت شد",
        "notification_history" to "اعلانهای هوشمند و روزانه",
        "analysis_positive" to "عالی بودی دیروز! میزان بازدهی شما نسبت به روزهای قبل ارتقا یافته است.",
        "analysis_neutral" to "وضعیت بازدهی شما پایدار است. به حرکت مداوم برای رسیدن به اهداف ادامه دهید!",
        "analysis_negative" to "کاهش جزئی در انجام کارها؛ نگران نباشید! هر تلاش کوچکی شایسته تقدیر است.",
        "weekly_overview" to "بررسی عملکرد برنامه‌ریزی هفتگی",
        "habit_tracker" to "عادت‌سنج روزانه",
        "add_habit" to "افزودن عادت جدید",
        "habit_title" to "نام عادت روزانه (مثال: ورزش مداوم)",
        "stats_summary" to "آنالیز دقیق بازدهی کارهای شما",
        "important_alerts" to "پیام‌های مهم و مناسبت امروز",
        "status_completed" to "تکمیل شده",
        "status_pending" to "در انتظار",
        "all_categories" to "همه کارها و پوشه‌ها",
        "search_advanced" to "جستجوی پیشرفته مأموریت‌ها",
        "search_query" to "کلمه کلیدی را وارد کنید...",
        "order_by" to "مرتب‌سازی بر اساس",
        "order_date" to "تاریخ انجام برنامه",
        "order_priority" to "میزان اهمیت و اولویت",
        "no_results" to "هیچ موردی با این مشخصات یافت نشد",
        "search" to "جستجو",
        "negative_habit" to "عادت منفی (پرهیز و ترک عادت)",
        "positive_habit" to "عادت مثبت (تلاش و استمرار)",
        "habit_type" to "ماهیت عادت",
        "group" to "همگام‌سازی اهداف خانوادگی",
        "group_code" to "کد اشتراک خانوادگی",
        "group_code_placeholder" to "مثال: FAMILY_AURA",
        "group_sync_status" to "همگام‌سازی گروهی",
        "all_priorities" to "همه اولویت‌ها",
        "no_tasks_today_completion" to "هیچ کاری امروز ثبت نکرده‌اید",
        "percentage_avoided" to "پرهیز شد",
        "history" to "تاریخچه",
        "performance" to "تاریخچه فعالیت و روزشمار مداوم",
        "no_history" to "هنوز هیچ فعالیتی ثبت نشده است.",
        "view_history" to "تاریخچه و نمودار روزانه",
        "habit_progress" to "نمودار بازدهی ماهیانه عادت",
        "show_full_history" to "مشاهده کل تاریخچه",
        "close" to "بستن",
        "all_records" to "تمامی ثبت‌ها",
        "days_total" to "مجموع روزهای انجام شده"
    )

    fun get(key: String): String {
        return if (activeLanguage == "fa") {
            fa[key] ?: en[key] ?: key
        } else {
            en[key] ?: key
        }
    }
}
